From: enginesd_debian_base  #Note image name here is too long 

#Only required if configuration overides base configuration params 
RUN /tmp/packing/scripts/early/locale &\\
    /tmp/packing/scripts/early/set_time_zone &\\
    /tmp/packing/scripts/early/repos &&\\
    
RUN ENGINES_PACKAGES="apache2" /tmp/packing/scripts/late/install-packages

ADD packing/late/ /